<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error Handlign</title>
</head>
<body>
<div id="wrapper">
  <p>Q1: Write a funciton that intentionally throws and erro and use a try-catch block to handle the error and log an appropriate message to the console.</p>
  
  <p>Q2: Create a  funciton that divides two numbers and throw an error if the denominator is zero. Use  a try-catch blok to handle this error</p>

  <p>Q3: Write a script that includes a try-catch block and a finally bloc. Log messages in the try, catch, and finally blocks to observe the execution flow</p>

  <p>Q4: Create a custom error class that extends the built-in Error class. Throw an instance of this custom error in a funciton and handle it using a try catch block</p>

  <p>Q5: Write a funciton that validates user input (e,g., checking if a string is not empty) and thros a custom error if the validation fails. Hanlde the custom error using a try-catch block</p>

  <p>Q6: Create a promise that randomly resolves or rejects. Use .catch() to handle the rejection and log an appropriate message to the console</p>

  <p>Q7: Use try-catch within an async funciton to handle error from a promise that randoley resolves or rejects, and log the error message</p>


  <p>Q8: Use the fetch API to request data from an invalid URL and handle the error using .catch() Log an appropriate error message to the console"</p>

  <p>Use the fetch API to request data from an invalid URL within an async funciton and handle the error using try-catch log and appropriate error message</p>



  




</div>


    <script src="app.js"></script>
</body>
</html>